//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapEntities : DbContext
    {
        public MapEntities()
            : base("name=MapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supan_PlaceTypes> Supan_PlaceTypes { get; set; }
        public virtual DbSet<Supan_Places> Supan_Places { get; set; }
        public virtual DbSet<Supan_RegionPoints> Supan_RegionPoints { get; set; }
        public virtual DbSet<Supan_Regions> Supan_Regions { get; set; }
    }
}
